const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),os=require('node:os'),{pathToFileURL}=require('node:url');
const file=path.resolve(__dirname,'../examples/rnn-lstm/index.html'),html=fs.readFileSync(file,'utf8'),ctx={};vm.createContext(ctx);vm.runInContext(html.match(/<script id="sequence-math">([\s\S]*?)<\/script>/)[1]+'\nthis.api={simulate,sequences};',ctx);const {simulate,sequences}=ctx.api,near=(a,b,t=1e-9)=>assert.ok(Math.abs(a-b)<t,`${a} vs ${b}`);
const p={u:.5,f:.95,i:1,o:1,mode:'manual'};
const a=simulate(sequences.pulse,p),g=Math.tanh(1);near(a[0].rh,g);near(a[0].c,g);near(a[0].h,Math.tanh(g));near(a[11].c,g*.95**11);
assert.ok(Math.abs(a[11].rh)<.001);assert.ok(a[11].c>.4);
for(const r of simulate(sequences.pulse,{...p,f:1}))near(r.c,g);
for(const r of simulate(sequences.pulse,{...p,i:0})){near(r.c,0);near(r.h,0)}
for(const r of simulate(sequences.pulse,{...p,o:0})){near(r.h,0);assert.ok(r.c>0)}
near(simulate(sequences.pulse,{...p,f:0})[1].c,0);
let checked=0;
for(const xs of Object.values(sequences))for(const mode of ['manual','fixed'])for(const u of [-1.5,.5,1.5]){const params={...p,u,mode},rows=simulate(xs,params),epsilon=1e-6,x1=Array.from(xs),x2=Array.from(xs);x1[0]+=epsilon;x2[0]-=epsilon;const plus=simulate(x1,params),minus=simulate(x2,params);rows.forEach((r,i)=>{near(r.dr,(plus[i].rh-minus[i].rh)/(2*epsilon),1e-7);near(r.dh,(plus[i].h-minus[i].h)/(2*epsilon),1e-7);near(r.dc,(plus[i].c-minus[i].c)/(2*epsilon),1e-7);near(r.c,r.kept+r.written);assert.ok(r.f>=0&&r.f<=1&&r.i>=0&&r.i<=1&&r.o>=0&&r.o<=1);assert.ok(Math.abs(r.rh)<=1&&Math.abs(r.h)<=1)});checked++}
console.log(`RNN/LSTM math passed: analytic pulse, gate extremes, state bounds and finite-difference sensitivities in ${checked} configurations.`);
async function browserCheck(){const {chromium}=require('playwright'),browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});try{const c=await browser.newContext({viewport:{width:1280,height:1000},serviceWorkers:'block'}),requests=[],errors=[];await c.route(/^https?:\/\//,r=>{requests.push(r.request().url());return r.abort()});const page=await c.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(file).href);assert.equal(await page.locator('#cellState').textContent(),'0.76159');await page.locator('#step').click();assert.equal(await page.locator('#currentStep').textContent(),'2 / 12');assert.equal(await page.locator('#cellState').textContent(),'0.72351');await page.locator('[data-t="12"]').click();assert.ok(+await page.locator('#cellState').textContent()>.4);assert.ok(+await page.locator('#rnnState').textContent()<.001);await page.locator('#outputGate').focus();await page.locator('#outputGate').press('Home');assert.equal(await page.locator('#hiddenState').textContent(),'0');assert.ok(+await page.locator('#cellState').textContent()>.4);await page.locator('#mode').selectOption('fixed');assert.equal(await page.locator('#forget').isDisabled(),true);assert.ok((await page.locator('#gateEquations').textContent()).includes('σ'));await page.locator('#sequence').selectOption('overwrite');await page.locator('[data-t="6"]').focus();await page.locator('[data-t="6"]').press('Enter');assert.equal(await page.locator('#editX').inputValue(),'-1');await page.locator('#editX').fill('0.5');await page.locator('#apply').click();assert.ok((await page.locator('#rnnFormula').textContent()).includes('0.5'));await page.locator('#reset').click();assert.equal(await page.locator('#mode').inputValue(),'manual');assert.equal(await page.locator('#outputGate').inputValue(),'1');await page.locator('#play').click();await page.waitForFunction(()=>document.getElementById('currentStep').textContent.startsWith('2 /'));await page.locator('#play').click();const stopped=await page.locator('#currentStep').textContent();await page.waitForTimeout(700);assert.equal(await page.locator('#currentStep').textContent(),stopped);await page.locator('#back').click();assert.equal(await page.locator('#currentStep').textContent(),'1 / 12');await page.screenshot({path:path.join(os.tmpdir(),'rnn-lstm-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);await page.screenshot({path:path.join(os.tmpdir(),'rnn-lstm-mobile.png'),fullPage:true});assert.deepEqual(requests,[]);assert.deepEqual(errors,[]);console.log('Browser passed: offline, known states, modes, gate sliders, editing, keyboard selection, playback/pause, reset and 390px layout.')}finally{await browser.close()}}
if(process.argv.includes('--browser'))browserCheck().catch(e=>{console.error(e);process.exitCode=1});
