const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const os = require('node:os');
const { pathToFileURL } = require('node:url');
const htmlPath = path.resolve(__dirname, '../examples/quantization/index.html');
const html = fs.readFileSync(htmlPath, 'utf8');
const scope = {};
vm.createContext(scope);
vm.runInContext(html.match(/<script id="quant-math">([\s\S]*?)<\/script>/)[1] + '\nthis.api={roundEven,calibration,quantize,calculate,datasets,floatApprox};', scope);
const { roundEven, calibration, quantize, calculate, datasets,floatApprox } = scope.api;
const near = (a,b) => assert.ok(Math.abs(a-b)<1e-10, `${a} != ${b}`);
near(floatApprox(1.0007,5,10),1+1/1024);near(floatApprox(1.0007,8,7),1);
near(floatApprox(70000,8,7),70144);assert.equal(floatApprox(70000,5,10),Infinity);
assert.equal(floatApprox(-70000,5,10),-Infinity);assert.equal(floatApprox(1e-8,5,10),0);
assert.equal(floatApprox(2**-24,5,10),2**-24);assert.equal(floatApprox(2**-25,5,10),0);
assert.equal(floatApprox(65504,5,10),65504);assert.equal(floatApprox(65520,5,10),Infinity);
assert.equal(floatApprox(2**-133,8,7),2**-133);assert.equal(floatApprox(2**-134,8,7),0);
near(floatApprox(1+1/2048,5,10),1);near(floatApprox(1+3/2048,5,10),1+2/1024);
for (const [x,y] of [[.5,0],[1.5,2],[2.5,2],[-.5,0],[-1.5,-2],[-2.5,-2]]) near(roundEven(x),y);
const p = { scale:.5,zero:0,qmin:-7,qmax:7 };
assert.equal(quantize(.73,p).q,1); near(quantize(.73,p).restored,.5);
assert.equal(quantize(5,p).q,7); near(quantize(5,p).error,-1.5); assert.equal(quantize(5,p).clipped,true);
const asym = calibration([-1,2],4,'asymmetric',1);
near(asym.scale,.2); assert.equal(asym.zero,5); near(quantize(0,asym).restored,0);
near(quantize(-1,asym).restored,-1); near(quantize(2,asym).restored,2);
assert.equal(calibration([0,0],4,'symmetric',1).scale,1);
let count=0;
for (const values of Object.values(datasets)) for (const bits of [2,4,8]) for (const mode of ['symmetric','asymmetric']) for (const factor of [.25,1,1.5]) for (const size of [4,16]) {
 const r=calculate(values,bits,mode,factor,size);
 near(r.mse,values.reduce((sum,x,i)=>sum+(r.rows[i].restored-x)**2,0)/values.length);
 assert.equal(r.payload,values.length*bits/8);
 assert.equal(r.metadata,values.length/size*(mode==='symmetric'?4:8));
 r.rows.forEach(row=>{const g=r.groups[row.group];assert.ok(Number.isInteger(row.q)&&row.q>=g.qmin&&row.q<=g.qmax);near(quantize(0,g).restored,0);assert.ok(Number.isFinite(row.restored));});count++;
}
assert.ok(calculate(datasets.positive,4,'asymmetric',1,16).mse < calculate(datasets.positive,4,'symmetric',1,16).mse);
assert.ok(calculate(datasets.outlier,4,'symmetric',1,4).mse < calculate(datasets.outlier,4,'symmetric',1,16).mse);
assert.ok(calculate(datasets.outlier,4,'symmetric',.25,16).clipped>0);
const changed=Array.from(datasets.balanced);changed[15]=8;
near(calculate(changed,4,'symmetric',1,4).groups[0].scale,calculate(datasets.balanced,4,'symmetric',1,4).groups[0].scale);
console.log(`Quantization math passed: analytic values, ties, clipping, zero, group isolation and ${count} combinations.`);
async function browserCheck(){
 const {chromium}=require('playwright');
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 try{
  const context=await browser.newContext({viewport:{width:1280,height:1000},serviceWorkers:'block'}),requests=[],errors=[];
  await context.route(/^https?:\/\//,r=>{requests.push(r.request().url());return r.abort()});
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(htmlPath).href);
  assert.ok((await page.locator('#semFormula').textContent()).includes('-10.5'));
  assert.ok((await page.locator('#semAssembly').textContent()).includes('M = 0101'));
  assert.ok((await page.locator('#semExpansion').textContent()).includes('0/2 + 1/4 + 0/8 + 1/16 = 0.3125'));
  assert.ok((await page.locator('#semEncoding').textContent()).includes('10010'));
  await page.locator('#semSign').selectOption('0');assert.ok((await page.locator('#semFormula').textContent()).includes('10.5'));
  await page.locator('#semExponent').focus();await page.locator('#semExponent').press('ArrowRight');assert.ok((await page.locator('#semFormula').textContent()).includes('21'));
  await page.locator('#semFraction').focus();await page.locator('#semFraction').press('Home');assert.ok((await page.locator('#semFormula').textContent()).includes('16'));
  assert.equal(await page.locator('#fpResult').textContent(),'1.0009765625');assert.equal(await page.locator('#bfResult').textContent(),'1');
  await page.locator('[data-float="70000"]').click();assert.equal(await page.locator('#fpResult').textContent(),'∞（溢出）');assert.equal(await page.locator('#bfResult').textContent(),'70144');
  await page.locator('[data-float="0.00000001"]').click();assert.equal(await page.locator('#fpResult').textContent(),'0');assert.notEqual(await page.locator('#bfResult').textContent(),'0');
  await page.locator('[data-float="1.0007"]').click();
  await page.locator('#floatInput').fill('-70000');assert.equal(await page.locator('#fpResult').textContent(),'−∞（溢出）');assert.equal(await page.locator('#bfResult').textContent(),'-70144');
  await page.locator('#floatInput').fill('');assert.ok((await page.locator('#fpResult').textContent()).includes('请输入'));
  await page.locator('[data-float="1.0007"]').click();
  await page.locator('#sem-demo').screenshot({path:path.join(os.tmpdir(),'quantization-sem.png')});
  await page.locator('#float-compare').screenshot({path:path.join(os.tmpdir(),'quantization-compare.png')});
  assert.equal(await page.locator('#integer').textContent(),'3');assert.equal(await page.locator('#restored').textContent(),'0.85714');assert.equal(await page.locator('#storage').textContent(),'12 B');
  const initialMse=await page.locator('#mse').textContent(),stair=await page.locator('#stair path').getAttribute('d');
  await page.locator('#probe').fill('1');assert.equal(await page.locator('#integer').textContent(),'4');assert.equal(await page.locator('#mse').textContent(),initialMse);
  await page.locator('#bits').selectOption('8');assert.notEqual(await page.locator('#stair path').getAttribute('d'),stair);assert.ok(+await page.locator('#mse').textContent()<+initialMse);
  await page.locator('#dataset').selectOption('positive');await page.locator('#mode').selectOption('asymmetric');await page.locator('#group').selectOption('4');assert.equal(await page.locator('#probeGroup option').count(),4);
  await page.locator('summary').click();await page.locator('[data-index="15"]').click();assert.equal(await page.locator('#probe').inputValue(),'3.2');assert.equal(await page.locator('#probeGroup').inputValue(),'3');
  await page.locator('[data-index="0"]').focus();await page.locator('[data-index="0"]').press('Enter');assert.equal(await page.locator('#probe').inputValue(),'0');
  await page.locator('#dataset').selectOption('outlier');await page.locator('#range').focus();await page.locator('#range').press('Home');assert.equal(await page.locator('#rangeValue').textContent(),'25%');assert.ok(parseInt(await page.locator('#clipped').textContent())>0);
  await page.locator('#format').selectOption('INT4');await page.locator('#billions').fill('70');assert.equal(await page.locator('#memory').textContent(),'35 GB');
  await page.locator('#format').selectOption('TF32');assert.equal(await page.locator('#memory').textContent(),'280 GB');
  await page.locator('#format').selectOption('NVFP4');assert.equal(await page.locator('#memory').textContent(),'39.375 GB');
  await page.locator('#reset').click();assert.equal(await page.locator('#mse').textContent(),initialMse);assert.equal(await page.locator('#stair path').getAttribute('d'),stair);
  await page.screenshot({path:path.join(os.tmpdir(),'quantization-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
  await page.screenshot({path:path.join(os.tmpdir(),'quantization-mobile.png'),fullPage:true});
  assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);console.log('Browser passed: offline file://, controls, known pipeline values, formats, keyboard, reset and 390px layout.');
 }finally{await browser.close()}
}
if(process.argv.includes('--browser'))browserCheck().catch(e=>{console.error(e);process.exitCode=1});
