const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),os=require('node:os');
const {pathToFileURL}=require('node:url');
const file=path.resolve(__dirname,'../examples/lora/index.html'),html=fs.readFileSync(file,'utf8'),scope={};vm.createContext(scope);vm.runInContext(html.match(/<script id="lora-math">([\s\S]*?)<\/script>/)[1]+'\nthis.api={multiply,initial,update,loss,gradients,trainStep,matvec,minimumLoss};',scope);
const {multiply,initial,update,loss,gradients,trainStep,matvec,minimumLoss}=scope.api;
const near=(a,b,t=1e-9)=>assert.ok(Math.abs(a-b)<t,`${a} vs ${b}`);
assert.equal(JSON.stringify(multiply([[1,2],[3,4]],[[5,6],[7,8]])),JSON.stringify([[19,22],[43,50]]));
near(minimumLoss(1,'three'),.015625);near(minimumLoss(2,'three'),.005625);near(minimumLoss(3,'three'),0);
const check=initial(2,'three');check.B[0][0]=.2;check.B[1][1]=-.1;const g=gradients(check.A,check.B,check.T,2),eps=1e-6;
for(const [M,G,i,j] of [[check.A,g.a,0,0],[check.A,g.a,1,3],[check.B,g.b,0,0],[check.B,g.b,3,1]]){const old=M[i][j];M[i][j]=old+eps;const plus=loss(check.A,check.B,check.T,2);M[i][j]=old-eps;const minus=loss(check.A,check.B,check.T,2);M[i][j]=old;near(G[i][j],(plus-minus)/(2*eps),1e-8)}
for(const task of ['one','three'])for(const r of [1,2,3,4]){
 const s=initial(r,task),original=JSON.stringify(s.W),scale=4/r;assert.ok(update(s.A,s.B,scale).every(row=>row.every(v=>v===0)));const before=loss(s.A,s.B,s.T,scale);let previous=before;
 for(let step=0;step<1800;step++){const n=trainStep(s.A,s.B,s.T,scale);assert.ok(n.loss<=previous+1e-14);s.A=n.A;s.B=n.B;previous=n.loss}
 assert.equal(JSON.stringify(s.W),original);assert.ok(previous<before*.9);assert.ok(previous>=minimumLoss(r,task)-1e-10);assert.ok(previous-minimumLoss(r,task)<1e-5,`${task},r=${r},loss=${previous}`);
 const x=[1,.5,-.5,.2,0,.3,-.2,.1],D=update(s.A,s.B,scale),merged=s.W.map((row,i)=>row.map((v,j)=>v+D[i][j])),base=matvec(s.W,x),adapter=matvec(s.B,matvec(s.A,x));matvec(merged,x).forEach((v,i)=>near(v,base[i]+scale*adapter[i]));
}
console.log('LoRA math passed: known product, finite-difference gradients, 8 training configurations, frozen W, theoretical bounds and merge equality.');
async function browserCheck(){const {chromium}=require('playwright');const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});try{const context=await browser.newContext({viewport:{width:1280,height:1000},serviceWorkers:'block'}),requests=[],errors=[];await context.route(/^https?:\/\//,r=>{requests.push(r.request().url());return r.abort()});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(file).href);
 assert.equal(await page.locator('#params').textContent(),'32');assert.equal(await page.locator('#ratio').textContent(),'50%');assert.equal(await page.locator('#loss').textContent(),'3.1250e-2');assert.equal(await page.locator('#floor').textContent(),'5.6250e-3');const frozen=await page.locator('[data-type=W]').allTextContents();
 await page.locator('#step').click();assert.equal(await page.locator('#steps').textContent(),'1');assert.ok(parseFloat(await page.locator('#loss').textContent())<.03125);assert.deepEqual(await page.locator('[data-type=W]').allTextContents(),frozen);
 await page.locator('#train').click();await page.waitForFunction(()=>+document.getElementById('steps').textContent>=80);await page.locator('#train').click();const stopped=await page.locator('#steps').textContent();await page.waitForTimeout(150);assert.equal(await page.locator('#steps').textContent(),stopped);
 await page.locator('[data-type=A][data-i="0"][data-j="0"]').click();await page.locator('#editValue').fill('0.75');await page.locator('#apply').click();assert.equal(await page.locator('[data-type=A][data-i="0"][data-j="0"]').textContent(),'0.75');assert.equal(await page.locator('#steps').textContent(),'0');
 await page.locator('[data-type=B][data-i="0"][data-j="0"]').focus();await page.locator('[data-type=B][data-i="0"][data-j="0"]').press('Enter');await page.locator('#editValue').fill('0.5');await page.locator('#apply').click();await page.locator('[data-type=D][data-i="0"][data-j="0"]').click();assert.ok((await page.locator('#element').textContent()).includes('0.5 × 0.75'));
 const output=await page.locator('#branchOutput').textContent();await page.locator('#inputX').focus();await page.locator('#inputX').press('Home');assert.notEqual(await page.locator('#branchOutput').textContent(),output);assert.equal(await page.locator('#branchOutput').textContent(),await page.locator('#mergedOutput').textContent());
 await page.locator('#alpha').focus();await page.locator('#alpha').press('End');assert.equal(await page.locator('#scale').textContent(),'8');await page.locator('#rank').selectOption('1');assert.equal(await page.locator('#params').textContent(),'16');assert.equal(await page.locator('#floor').textContent(),'1.5625e-2');await page.locator('#task').selectOption('one');assert.equal(await page.locator('#floor').textContent(),'0.0000e+0');
 await page.locator('#rank').selectOption('4');assert.equal(await page.locator('#ratio').textContent(),'100%');await page.locator('#dimIn').fill('512');await page.locator('#dimOut').fill('512');assert.ok((await page.locator('#largeCounts').textContent()).includes('1.563%'));
 await page.locator('#rank').selectOption('2');await page.locator('#task').selectOption('three');await page.locator('#alpha').press('Home');await page.locator('#reset').click();assert.equal(await page.locator('#steps').textContent(),'0');assert.equal(await page.locator('#frozenCheck').textContent(),'未变化');
 await page.screenshot({path:path.join(os.tmpdir(),'lora-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);await page.screenshot({path:path.join(os.tmpdir(),'lora-mobile.png'),fullPage:true});assert.deepEqual(requests,[]);assert.deepEqual(errors,[]);console.log('LoRA browser passed: offline file://, training/pause, edits, keyboard, sliders, rank/task, merge outputs, reset and 390px layout.');}finally{await browser.close()}}
if(process.argv.includes('--browser'))browserCheck().catch(e=>{console.error(e);process.exitCode=1});
