const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : {}),headless:true});
 const context=await browser.newContext({viewport:{width:1280,height:1000},serviceWorkers:'block'});
 const requests=[],errors=[];
 await context.route(/^https?:\/\//,route=>{requests.push(route.request().url());return route.abort();});
 await context.addInitScript(()=>{window.drawCalls=[];for(const name of ['strokeRect','fillText','translate','scale']){const original=CanvasRenderingContext2D.prototype[name];CanvasRenderingContext2D.prototype[name]=function(...args){window.drawCalls.push([name,...args]);return original.apply(this,args);};}});
 const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
 await page.goto(require('node:url').pathToFileURL(require('node:path').resolve(__dirname,'../examples/yolo-dataset-viewer/index.html')).href);
 await page.getByRole('button',{name:'开始标注',exact:true}).click();
 await page.getByText('请先上传图片和标注文件！',{exact:true}).waitFor();
 await page.locator('#imageUpload').setInputFiles({name:'test.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300"><rect width="400" height="300" fill="white"/></svg>')});
 await page.waitForFunction(()=>document.querySelector('canvas').width===400);
 await page.locator('#annotationUpload').setInputFiles({name:'test.txt',mimeType:'text/plain',buffer:Buffer.from('0 0.5 0.5 0.5 0.5\n1 0.25 0.25 0.2 0.2\n')});
 await page.getByRole('button',{name:'开始标注',exact:true}).click();
 await page.getByText('标注处理成功！可以使用滑块调节缩放，按住鼠标拖动画布。',{exact:true}).waitFor();
 const calls=await page.evaluate(()=>window.drawCalls);
 assert.ok(calls.some(c=>JSON.stringify(c)===JSON.stringify(['strokeRect',100,75,200,150])));
 assert.ok(calls.some(c=>c[0]==='fillText'&&c[1]==='class 1'));
 const pixel=await page.evaluate(()=>Array.from(document.querySelector('canvas').getContext('2d').getImageData(100,100,1,1).data));
 assert.deepEqual(pixel,[0,255,0,255]);
 const slider=page.getByRole('slider');await slider.focus();await slider.press('ArrowRight');
 await page.waitForFunction(()=>window.drawCalls.some(c=>c[0]==='scale'&&c[1]===1.1));
 const box=await page.locator('canvas').boundingBox();
 await page.mouse.move(box.x+50,box.y+50);await page.mouse.down();await page.mouse.move(box.x+90,box.y+80,{steps:5});await page.mouse.up();
 await page.waitForFunction(()=>window.drawCalls.some(c=>c[0]==='translate'&&c[1]===40&&c[2]===30));
 await page.getByRole('button',{name:'重置视图',exact:true}).click();
 assert.equal(await slider.inputValue(),'1');
 await page.screenshot({path:require('node:os').tmpdir()+'/yolo-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
 await page.screenshot({path:require('node:os').tmpdir()+'/yolo-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
 console.log('PASS: offline file://, upload, known box coordinates and pixels, zoom, drag, reset; no external requests or runtime errors.');
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
